"""The spoken AI disclosure, in two pieces.

Apple requires AI disclosure in three places when the audio is machine
generated: the show metadata, each episode's metadata, and the content itself.
The first two are the feed's `description` and the per-episode attribution
line; this module is the third.

It is two pieces because those two jobs pull in opposite directions. A listener
needs to know inside the first few seconds that nobody here is a person, and
that has to be one short sentence -- an episode that opens by reading out five
titles and their authors loses the listener before the conversation starts. But
the works an episode drew on deserve to be *said*, not counted, and the natural
place to read credits is where credits go.

So: an opener that discloses and nothing else, and closing credits that name
every work and disclose again. Turning `[intro] opener` off leaves only the
credits, which is the honest version of "put it at the end" -- worth knowing
that anyone who stops early then never hears it.

Two things are deliberate in both:

- The wording is a template, not something the script model writes. A
  compliance statement that a model paraphrases is a compliance statement that
  can drift, and nothing downstream would notice.
- Each is synthesized in its own single-voice call rather than as an extra
  speaker in the conversation. The multi-speaker API takes *exactly* two
  speaker configs ("Exactly two speaker voice configurations must be
  provided"), so a third voice cannot come from the same call. A separate call
  also keeps the announcer out of the host chunking, so neither piece is split
  across a chunk boundary or reworded to fit the dialogue.

Each rendered text is stored next to its WAV. Editing a paper's title or
authors changes the credits, and the mismatch is what triggers a
re-synthesis; otherwise a resumed run reuses what is already on disk.
"""

import logging
import re

import db
from config import CHUNKS_DIR
from prose import author_credit, decaps
from . import NoAudioError, PipelineError
from .gemini import call_with_retry, client, record_cost

log = logging.getLogger("paperpod.intro")

# The opener keeps the original filenames: an episode already on disk has an
# intro.wav, and renaming would orphan it into a re-synthesis nobody asked for.
OPENER = "intro"
CREDITS = "credits"
PIECES = (OPENER, CREDITS)

WAV_NAME = "intro.wav"   # the opener
TEXT_NAME = "intro.txt"

DEFAULT_OPENER = "This is Paperpod, an AI generated podcast."
# $WORKS is every work the episode drew on, named and credited in turn. Read at
# the end, where a list is something a listener can sit through rather than
# something standing between them and the episode.
DEFAULT_CREDITS = (
    "That was Paperpod. This episode was generated by AI — the script, the "
    "voices, and this announcement. It drew on $WORKS."
)
DEFAULT_VOICE = "Charon"

# Style direction for the announcer. Kept away from the disclosure text itself
# so the model cannot mistake one for the other.
DIRECTION = (
    "Read the following announcement aloud, once, exactly as written. Calm, "
    "clear, unhurried announcer delivery. Do not add words, greetings, or "
    "commentary."
)


def enabled(cfg: dict) -> bool:
    return bool(cfg.get("intro", {}).get("enabled", True))


def _voice(cfg: dict) -> str:
    return (cfg.get("intro", {}).get("voice") or DEFAULT_VOICE).strip() or DEFAULT_VOICE


def _credit_one(paper) -> str:
    """One work, named and credited, as the announcer says it."""
    title = decaps((paper["title"] or "").strip()) or "an untitled paper"
    authors = db.episode_authors(paper)
    return f"{title}, by {author_credit(authors)}".rstrip(",. ") if authors else title


def _join(parts: list[str]) -> str:
    if len(parts) == 1:
        return parts[0]
    return f"{'; '.join(parts[:-1])}; and {parts[-1]}"


def has_opener(cfg: dict) -> bool:
    """Whether anything is said before the conversation.

    Off means the only spoken disclosure is at the end, which is a real choice
    with a real cost: a listener who stops before the credits never hears it.
    The feed and episode metadata still carry it either way.
    """
    return bool(cfg.get("intro", {}).get("opener", True))


def opener_text(ep, cfg: dict) -> str | None:
    """The one sentence before the conversation, or None.

    Deliberately says nothing about which papers: the works are read out in
    full at the end, and an episode that opens with a bibliography loses the
    listener before the hosts have said anything.
    """
    if not enabled(cfg) or ep is None or not has_opener(cfg):
        return None
    return _tidy(cfg.get("intro", {}).get("opener_template") or DEFAULT_OPENER)


def credits_text(ep, cfg: dict, papers=None) -> str | None:
    """The closing credits: every work named and credited, and the disclosure.

    Takes the episode row rather than an id, because the library renders one of
    these per row. `papers` is looked up when not supplied, so a caller that
    already has them does not pay for the query twice.

    References are read out too. Counting them was the cheaper option and it
    made the episode's own basis into a footnote -- if a work was worth drawing
    on, it is worth naming.
    """
    if not enabled(cfg) or ep is None:
        return None

    icfg = cfg.get("intro", {})
    if papers is None:
        try:
            papers = db.papers_for(ep["id"])
        except (IndexError, KeyError, TypeError):
            papers = []
    # Principals first, then the rest, each in running order -- the same order
    # the show notes list them in.
    ordered = ([p for p in papers if p["role"] == db.PRINCIPAL]
               + [p for p in papers if p["role"] != db.PRINCIPAL])

    if ordered:
        works = _join([_credit_one(p) for p in ordered])
    else:
        # No papers attached at all: pre-split rows reaching this through the
        # merged view still have a title and authors of their own.
        title = decaps((ep["title"] or "").strip()) or "an untitled paper"
        authors = db.episode_authors(ep)
        works = f"{title}, by {author_credit(authors)}".rstrip(",. ") if authors else title

    template = icfg.get("credits_template") or DEFAULT_CREDITS
    return _tidy(template.replace("$WORKS", works))


def _tidy(text: str) -> str:
    # "Smith et al." already ends a sentence, so the template's own full stop
    # would double it. Collapse a bare pair only -- an ellipsis in a title is
    # a legitimate three.
    return re.sub(r"(?<!\.)\.\.(?!\.)", ".", text).strip()


def text_for(piece: str, ep, cfg: dict, papers=None) -> str | None:
    return (opener_text(ep, cfg) if piece == OPENER
            else credits_text(ep, cfg, papers))


def wav_path(episode_id: str, piece: str = OPENER):
    return CHUNKS_DIR / episode_id / f"{piece}.wav"


def recorded_text(episode_id: str, piece: str = OPENER) -> str | None:
    """What the WAV on disk actually says, or None if there is no such audio.

    Compared against the current text to spot audio announcing a title or
    authors someone has since edited -- or, now, an episode whose papers have
    changed since its credits were recorded.
    """
    wav = wav_path(episode_id, piece)
    if not wav.exists() or wav.stat().st_size <= 44:
        return None
    try:
        return (CHUNKS_DIR / episode_id / f"{piece}.txt").read_text(encoding="utf-8")
    except OSError:
        return None


def is_stale(episode_id: str, ep, cfg: dict) -> bool:
    """Whether either spoken piece says something the episode no longer means.

    Either, not both: credits that name a paper the episode dropped are as
    wrong as an opener would be, and there is nothing in audio to reveal it.
    """
    for piece in PIECES:
        wanted = text_for(piece, ep, cfg)
        if wanted and recorded_text(episode_id, piece) != wanted:
            return True
    return False


def synthesize_intro(episode_id: str, cfg: dict) -> None:
    """Record both spoken pieces, skipping any that already match their text.

    Failure raises: an episode published without the disclosure is a compliance
    problem, not a cosmetic gap like a missing dialogue chunk.
    """
    ep = db.get_episode(episode_id)
    if not ep:
        raise PipelineError("no such episode")
    papers = db.papers_for(episode_id)

    out_dir = CHUNKS_DIR / episode_id
    out_dir.mkdir(parents=True, exist_ok=True)
    for piece in PIECES:
        text = text_for(piece, ep, cfg, papers)
        if not text:
            # Turning the opener off leaves whatever was recorded for it lying
            # around; assembly goes by the config, so it is inert.
            continue

        wav = out_dir / f"{piece}.wav"
        stamp = out_dir / f"{piece}.txt"
        if wav.exists() and wav.stat().st_size > 44:
            try:
                if stamp.read_text(encoding="utf-8") == text:
                    log.info("%s already synthesized for %s, skipping", piece,
                             episode_id)
                    continue
            except OSError:
                pass
            log.info("%s text changed for %s, re-synthesizing", piece, episode_id)

        db.set_progress(episode_id, f"synthesizing {piece}")
        _synthesize(episode_id, text, wav, cfg)
        stamp.write_text(text, encoding="utf-8")


def _synthesize(episode_id: str, text: str, wav, cfg: dict) -> None:
    from google.genai import types

    from .tts import _extract_audio, _write_wav, model_for

    model = model_for(episode_id, cfg)
    speech_config = types.SpeechConfig(
        # Single-voice output. Mutually exclusive with the multi-speaker config
        # the two-host chunks use, which is why this is its own call.
        voice_config=types.VoiceConfig(
            prebuilt_voice_config=types.PrebuiltVoiceConfig(voice_name=_voice(cfg))
        )
    )

    def once():
        resp = client().models.generate_content(
            model=model,
            contents=f"{DIRECTION}\n\n{text}",
            config=types.GenerateContentConfig(
                response_modalities=["AUDIO"],
                speech_config=speech_config,
            ),
        )
        record_cost(episode_id, model, resp, cfg, stage="intro")
        return _extract_audio(resp)

    data, mime = call_with_retry(
        once, cfg, model, label="tts intro", extra_retryable=(NoAudioError,),
    )
    _write_wav(wav, data, mime)
